[package]
name = "minuit-py"
version = "0.1.0"
edition = "2021"

[dependencies.pyo3]
version = "^0.15.1"
features = ["extension-module"]

[dependencies.minuit]
version = "^0.2.0"

[lib]
name = "_minuit_py"
crate-type = ["cdylib"]